spring:
  cloud:
    stream:
      bindings:
        transactionProcessor-in-0:
          destination: credit-card-transactions
          group: notifications
          consumer:
            concurrency: 10
        transactionProcessor-out-0:
          destination: email-requests
      kafka:
        binder:
          transaction:
            transaction-id-prefix: tx-
          required-acks: all

server:
  port: 0

logging:
  pattern:
    console: "[%blue(%18thread)] %date{HH:mm.ss:SSS} [%cyan(%45logger{45})] %highlight(%-5level) %yellow(%X) %msg%n"
