spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094

    streams:
      application-id: quotes

logging:
  level:
    org.springframework.kafka.config.StreamsBuilderFactoryBean: debug
