spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    properties:
      schema.registry.url: http://localhost:8085
    streams:
      application-id: grouping_avro_app

logging:
  level:
    org.springframework.kafka.config.StreamsBuilderFactoryBean: debug
