spring:
  cloud:
    stream:
      bindings:
        transactionConsumer-in-0:
          destination: credit-card-transactions
          group: fraud-detection
          consumer:
            instance-index-list: 7
            instance-count: 10
            partitioned: true

      kafka:
        bindings:
          transactionConsumer-in-0:
            consumer:
              auto-rebalance-enabled: false
server:
  port: 0

logging:
  pattern:
    console: "[%blue(%18thread)] %date{HH:mm.ss:SSS} [%cyan(%45logger{45})] %highlight(%-5level) %yellow(%X) %msg%n"
