spring:
  cloud:
    stream:
      bindings:
        transactionGenerator-out-0:
          destination: credit-card-transactions
          producer:
            poller:
              fixed-delay: 250
            partition-count: 10

      kafka:
        binder:
          replication-factor: 3

server:
  port: 0
