spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    producer:
      # some common settings have strongly typed configuration
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      client-id: ymlConfiguredProducer
      compression-type: lz4
      acks: all
      # the rest you specify as typeless properties
      properties:
        linger.ms: 100
