spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    producer:
      transaction-id-prefix: tx-
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      isolation-level: read_committed
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.luxoft.*"

logging:
  level:
    org.springframework.transaction: trace
    org.springframework.kafka.transaction: debug
